import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { UserCheck, Check, X, RefreshCw } from "lucide-react";
import Sidebar from "../../layout/Sidebar";
import PageHeader from "../../common/pagesAssets/PageHeader";
import { useAuth } from "../../../context/AuthContext";
import { useToast } from "../../../context/ToastContext";
import { trainerAPI } from "../../../services/api";
import { trainerNavItems, trainerSidebarProps } from "./trainerNavigation";

const DUMMY_APPLICATIONS = [
 { id:"dummy-app-1", student:{ user:{ firstName:"Lina", lastName:"Hassan" }, major:"Software Engineering" }, opportunity:{ title:"Frontend Development Internship" } },
 { id:"dummy-app-2", student:{ user:{ firstName:"Omar", lastName:"Khaled" }, major:"Computer Science" }, opportunity:{ title:"Frontend Development Internship" } },
 { id:"dummy-app-3", student:{ user:{ firstName:"Sara", lastName:"Ali" }, major:"Information Technology" }, opportunity:{ title:"Frontend Development Internship" } },
 { id:"dummy-app-4", student:{ user:{ firstName:"Yousef", lastName:"Nasser" }, major:"Software Engineering" }, opportunity:{ title:"Frontend Development Internship" } },
];

export default function TrainerApplications(){
 const navigate=useNavigate();const {user,logout}=useAuth();const {showToast}=useToast();const [apps,setApps]=useState([]);const [loading,setLoading]=useState(true);const [usingDummy,setUsingDummy]=useState(false);const [acting,setActing]=useState(null);const fullName=`${user?.firstName||""} ${user?.lastName||""}`.trim()||"Trainer";
 const load=async()=>{setLoading(true);try{const r=await trainerAPI.getPendingApplications(1,50);const data=r?.data||r||[];setApps(Array.isArray(data)?data:[]);setUsingDummy(false)}catch(e){console.warn("Trainer applications API unavailable; using temporary dummy data.",e);setApps(DUMMY_APPLICATIONS);setUsingDummy(true)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const action=async(id,type)=>{setActing(id);const isDummy=String(id).startsWith("dummy-");try{if(!isDummy){if(type==="approve")await trainerAPI.approveApplication(id);else await trainerAPI.rejectApplication(id)}setApps(p=>p.filter(a=>a.id!==id));showToast(type==="approve"?"Application approved.":"Application rejected.","success")}catch(e){showToast(e?.message||`Failed to ${type} application.`,"error")}finally{setActing(null)}};
 const signOut=()=>{logout();navigate("/login")};
 return <div className="flex h-screen w-full overflow-hidden bg-[#F7F9FC]"><Sidebar navItems={trainerNavItems} footerItems={[]} user={{name:fullName,role:"Company Trainer",avatar:user?.profileImage||""}} {...trainerSidebarProps} onSignOut={signOut}/><main className="flex-1 overflow-y-auto"><div className="mx-auto max-w-[1240px] px-5 py-5 sm:px-7 lg:px-8 lg:py-7"><PageHeader loading={loading} profile={user} fullName={fullName} studentUser={{name:fullName,role:"Company Trainer",avatar:user?.profileImage||""}} searchValue="" onSearchChange={()=>{}} chatBadge={0} notificationBadge={apps.length}/><div className="mt-6 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#7B8497]">Review queue</p><h1 className="mt-1 text-2xl font-extrabold text-[#172033]">Applications</h1><p className="mt-1 text-sm text-[#7B8497]">Review students requesting to join your internship.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-[#E4E8EF] bg-white px-4 py-2.5 text-xs font-bold"><RefreshCw size={15}/> Refresh</button></div>{usingDummy&&<div className="mt-4 rounded-xl border border-[#F6D8AD] bg-[#FFFBF5] px-4 py-3 text-xs text-[#8A5A00]">Backend applications endpoint is not available yet. Temporary demo applications are shown for the UI.</div>}<div className="mt-5 overflow-hidden rounded-2xl border border-[#E9EDF4] bg-white">{loading?<div className="space-y-3 p-5">{[1,2,3].map(i=><div key={i} className="h-20 animate-pulse rounded-xl bg-[#F3F5F8]"/>)}</div>:apps.length===0?<div className="p-14 text-center"><UserCheck className="mx-auto text-[#C8CFDA]"/><p className="mt-3 text-sm font-bold text-[#596274]">No pending applications</p></div>:<div className="divide-y divide-[#EEF1F5]">{apps.map(a=>{const s=a.student||{};const name=`${s.user?.firstName||""} ${s.user?.lastName||""}`.trim()||"Student";return <div key={a.id} className="flex flex-col gap-4 px-5 py-4 sm:flex-row sm:items-center"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#FFF4E5] text-sm font-extrabold text-[#A45A00]">{name.charAt(0)}</div><div className="min-w-0 flex-1"><p className="text-sm font-bold text-[#172033]">{name}</p><p className="mt-1 text-xs text-[#7B8497]">{s.major||"Major not provided"}{a.opportunity?.title?` · ${a.opportunity.title}`:""}</p></div><div className="flex gap-2"><button disabled={acting===a.id} onClick={()=>action(a.id,"reject")} className="inline-flex items-center gap-1.5 rounded-xl border border-[#F3D1D1] px-3 py-2 text-xs font-bold text-[#C33B3B] disabled:opacity-50"><X size={14}/> Reject</button><button disabled={acting===a.id} onClick={()=>action(a.id,"approve")} className="inline-flex items-center gap-1.5 rounded-xl bg-[#16833A] px-3 py-2 text-xs font-bold text-white disabled:opacity-50"><Check size={14}/> Approve</button></div></div>})}</div>}</div></div></main></div>;
}
