import React, { useEffect, useMemo, useState } from "react";
import { ClipboardList, Plus, Search, X, RefreshCw, AlertCircle, Clock3, CheckCircle2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import Sidebar from "../../layout/Sidebar";
import { useAuth } from "../../../context/AuthContext";
import { useToast } from "../../../context/ToastContext";
import { trainerAPI } from "../../../services/api";

const COLORS = { primary: "#0475FB", text: "#172033", muted: "#7B8497", border: "#E9EDF4" };
const navItems = [
  { label: "Dashboard", icon: () => <span>▦</span>, path: "/company/trainer/dashboard" },
  { label: "Trainees", icon: () => <span>◉</span>, path: "/company/trainer/students" },
  { label: "Tasks", icon: ClipboardList, path: "/company/trainer/tasks" },
  { label: "Applications", icon: () => <span>◌</span>, path: "/company/trainer/applications" },
];
const statusStyle = { "Not Started": "bg-slate-100 text-slate-600", "In Progress": "bg-blue-50 text-blue-700", Submitted: "bg-amber-50 text-amber-700", "Under Review": "bg-violet-50 text-violet-700", Completed: "bg-green-50 text-green-700" };
const normalize = (result) => result?.data || result || [];

export default function TrainerTasks() {
  const navigate = useNavigate(); const { user, logout } = useAuth(); const { showToast } = useToast();
  const [tasks, setTasks] = useState([]); const [students, setStudents] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("All"); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ title: "", description: "", studentId: "", dueDate: "" });

  const load = async () => { setLoading(true); setError(""); try { const [taskResult, studentResult] = await Promise.all([trainerAPI.getTasks(1, 50), trainerAPI.getMyStudents(1, 50)]); setTasks(normalize(taskResult)); setStudents(normalize(studentResult)); } catch (err) { setError(err?.message || "Unable to load task data."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);

  const filtered = useMemo(() => tasks.filter((task) => { const title = (task?.title || task?.name || "").toLowerCase(); const status = task?.status || "Not Started"; return `${title} ${(task?.student?.user?.firstName || "")} ${(task?.student?.user?.lastName || "")}`.toLowerCase().includes(search.toLowerCase()) && (filter === "All" || status === filter); }), [tasks, search, filter]);
  const fullName = `${user?.firstName || ""} ${user?.lastName || ""}`.trim() || "Trainer";

  const create = async (e) => { e.preventDefault(); if (!form.title.trim()) return; setSaving(true); try { await trainerAPI.createTask({ title: form.title.trim(), description: form.description.trim(), studentId: form.studentId || undefined, dueDate: form.dueDate || undefined }); showToast("Task created successfully.", "success"); setOpen(false); setForm({ title: "", description: "", studentId: "", dueDate: "" }); load(); } catch (err) { showToast(err?.message || "Failed to create task.", "error"); } finally { setSaving(false); } };

  return <div className="flex min-h-screen w-full bg-[#F5F7FB] font-['Inter'] text-[#172033]">
    <Sidebar navItems={navItems} footerItems={[]} user={{ name: fullName, role: "Company Trainer", avatar: user?.profileImage || "" }} profilePath="/company/trainer/dashboard" onSignOut={() => { logout(); navigate("/login"); }} brandPath="/company/trainer/dashboard" storageKey="sidebar-company-trainer" />
    <main className="min-w-0 flex-1 overflow-y-auto"><div className="mx-auto max-w-[1240px] px-5 py-6 sm:px-8 lg:px-10">
      <header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[#7B8497]">Work management</p><h1 className="mt-1 text-2xl font-extrabold">Tasks</h1><p className="mt-1 text-sm text-[#7B8497]">Create assignments, track deadlines, and review trainee work.</p></div><button onClick={() => setOpen(true)} className="flex items-center justify-center gap-2 rounded-xl bg-[#0475FB] px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-[#035CC9]"><Plus size={17}/> Create task</button></header>
      <section className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-4" style={{ borderColor: COLORS.border }}><p className="text-xs text-[#7B8497]">Total tasks</p><p className="mt-1 text-2xl font-extrabold">{tasks.length}</p></div><div className="rounded-2xl border bg-white p-4" style={{ borderColor: COLORS.border }}><p className="text-xs text-[#7B8497]">In progress</p><p className="mt-1 text-2xl font-extrabold">{tasks.filter(t => (t?.status || "Not Started") === "In Progress").length}</p></div><div className="rounded-2xl border bg-white p-4" style={{ borderColor: COLORS.border }}><p className="text-xs text-[#7B8497]">Awaiting review</p><p className="mt-1 text-2xl font-extrabold">{tasks.filter(t => ["Submitted", "Under Review"].includes(t?.status)).length}</p></div></section>
      <section className="mt-5 rounded-2xl border bg-white p-4 shadow-sm" style={{ borderColor: COLORS.border }}><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="relative flex-1 lg:max-w-md"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#9AA3B2]"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search tasks or trainees..." className="h-10 w-full rounded-xl border bg-[#F8FAFC] pl-10 pr-4 text-sm outline-none focus:border-[#0475FB]" style={{ borderColor: COLORS.border }}/></div><div className="flex flex-wrap items-center gap-2">{["All", "Not Started", "In Progress", "Submitted", "Completed"].map(item => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-3 py-1.5 text-[11px] font-bold ${filter === item ? "bg-[#EAF3FF] text-[#0475FB]" : "bg-[#F5F7FB] text-[#7B8497]"}`}>{item}</button>)}<button onClick={load} className="rounded-lg border p-2 text-[#7B8497] hover:bg-[#F8FAFC]" style={{ borderColor: COLORS.border }} title="Refresh"><RefreshCw size={14}/></button></div></div></section>
      {error && <div className="mt-4 flex gap-2 rounded-xl border border-red-100 bg-red-50 p-3 text-xs text-red-700"><AlertCircle size={15}/>{error}</div>}
      <section className="mt-5 overflow-hidden rounded-2xl border bg-white shadow-sm" style={{ borderColor: COLORS.border }}>{loading ? <div className="p-10 text-center text-sm text-[#7B8497]">Loading tasks...</div> : filtered.length === 0 ? <div className="p-12 text-center"><ClipboardList size={30} className="mx-auto text-[#C9D0DB]"/><p className="mt-3 text-sm font-bold">No tasks match your filters</p><p className="mt-1 text-xs text-[#7B8497]">Create a task or change the current filter.</p></div> : <div className="divide-y">{filtered.map(task => { const status = task?.status || "Not Started"; const name = `${task?.student?.user?.firstName || ""} ${task?.student?.user?.lastName || ""}`.trim() || task?.student?.name || "Unassigned"; return <div key={task.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 items-start gap-3"><div className="mt-0.5 rounded-lg bg-[#EAF3FF] p-2 text-[#0475FB]"><ClipboardList size={16}/></div><div className="min-w-0"><p className="truncate text-sm font-extrabold">{task?.title || task?.name || "Untitled task"}</p><p className="mt-1 truncate text-xs text-[#7B8497]">{name}{task?.dueDate ? ` · Due ${new Date(task.dueDate).toLocaleDateString()}` : ""}</p></div></div><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-bold ${statusStyle[status] || "bg-slate-100 text-slate-600"}`}>{status}</span><div className="flex items-center gap-1 text-xs text-[#7B8497]"><Clock3 size={14}/>{task?.dueDate ? new Date(task.dueDate).toLocaleDateString() : "No deadline"}</div></div>; })}</div>}</section>
    </div></main>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#172033]/30 p-4" onMouseDown={e => e.target === e.currentTarget && setOpen(false)}><form onSubmit={create} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-lg font-extrabold">Create task</h2><p className="mt-1 text-xs text-[#7B8497]">Give the trainee a clear outcome and deadline.</p></div><button type="button" onClick={() => setOpen(false)} className="rounded-lg p-2 text-[#7B8497] hover:bg-[#F5F7FB]"><X size={18}/></button></div><div className="mt-5 space-y-4"><label className="block"><span className="text-xs font-bold">Task title</span><input required value={form.title} onChange={e => setForm({...form,title:e.target.value})} placeholder="e.g. Build authentication UI" className="mt-1.5 h-10 w-full rounded-xl border px-3 text-sm outline-none focus:border-[#0475FB]" style={{borderColor:COLORS.border}}/></label><label className="block"><span className="text-xs font-bold">Description</span><textarea value={form.description} onChange={e => setForm({...form,description:e.target.value})} rows={4} placeholder="Describe the expected result..." className="mt-1.5 w-full resize-none rounded-xl border p-3 text-sm outline-none focus:border-[#0475FB]" style={{borderColor:COLORS.border}}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="text-xs font-bold">Assign to</span><select value={form.studentId} onChange={e => setForm({...form,studentId:e.target.value})} className="mt-1.5 h-10 w-full rounded-xl border bg-white px-3 text-sm outline-none" style={{borderColor:COLORS.border}}><option value="">Select trainee</option>{students.map(s => <option key={s.id} value={s.id}>{`${s?.student?.user?.firstName || ""} ${s?.student?.user?.lastName || ""}`.trim() || "Student"}</option>)}</select></label><label className="block"><span className="text-xs font-bold">Deadline</span><input type="date" value={form.dueDate} onChange={e => setForm({...form,dueDate:e.target.value})} className="mt-1.5 h-10 w-full rounded-xl border px-3 text-sm outline-none" style={{borderColor:COLORS.border}}/></label></div></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-xl border px-4 py-2 text-sm font-bold" style={{borderColor:COLORS.border}}>Cancel</button><button disabled={saving} className="flex items-center gap-2 rounded-xl bg-[#0475FB] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? "Creating..." : <><CheckCircle2 size={16}/> Create task</>}</button></div></form></div>}
  </div>;
}
