import React from "react";
import { ArrowLeft, ClipboardList, GraduationCap, UserRound, CalendarDays } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import Sidebar from "../../layout/Sidebar";
import { useAuth } from "../../../context/AuthContext";

const navItems = [
  { label: "Dashboard", icon: () => <span>▦</span>, path: "/company/trainer/dashboard" },
  { label: "Trainees", icon: GraduationCap, path: "/company/trainer/students" },
  { label: "Tasks", icon: ClipboardList, path: "/company/trainer/tasks" },
  { label: "Applications", icon: () => <span>◌</span>, path: "/company/trainer/applications" },
];
const getName = (s) => `${s?.student?.user?.firstName || ""} ${s?.student?.user?.lastName || ""}`.trim() || "Student";

export default function TrainerStudentDetails() {
  const navigate = useNavigate(); const { state } = useLocation(); const { user, logout } = useAuth(); const student = state?.student;
  const fullName = `${user?.firstName || ""} ${user?.lastName || ""}`.trim() || "Trainer";
  if (!student) return <div className="flex min-h-screen items-center justify-center bg-[#F5F7FB] p-6 text-center"><div><p className="font-bold">Trainee details are unavailable</p><p className="mt-1 text-sm text-[#7B8497]">Open the trainee from your trainee list.</p><button onClick={()=>navigate("/company/trainer/students")} className="mt-4 rounded-xl bg-[#0475FB] px-4 py-2 text-sm font-bold text-white">Back to trainees</button></div></div>;
  const name = getName(student); const major = student?.student?.major || "Major not provided";
  return <div className="flex min-h-screen w-full bg-[#F5F7FB] font-['Inter'] text-[#172033]"><Sidebar navItems={navItems} footerItems={[]} user={{name:fullName,role:"Company Trainer",avatar:user?.profileImage||""}} profilePath="/company/trainer/dashboard" onSignOut={()=>{logout();navigate("/login")}} brandPath="/company/trainer/dashboard" storageKey="sidebar-company-trainer"/><main className="min-w-0 flex-1"><div className="mx-auto max-w-[1000px] px-5 py-7 sm:px-8"><button onClick={()=>navigate("/company/trainer/students")} className="mb-6 flex items-center gap-2 text-xs font-bold text-[#0475FB]"><ArrowLeft size={15}/> Back to trainees</button><section className="rounded-2xl border bg-white p-6 shadow-sm" style={{borderColor:"#E9EDF4"}}><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-[#EAF3FF] text-xl font-extrabold text-[#0475FB]">{name.charAt(0)}</div><div><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[#7B8497]">Trainee overview</p><h1 className="mt-1 text-2xl font-extrabold">{name}</h1><p className="mt-1 text-sm text-[#7B8497]">{major}</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[#F8FAFC] p-4"><UserRound size={17} className="text-[#0475FB]"/><p className="mt-3 text-[10px] font-bold uppercase text-[#7B8497]">Status</p><p className="mt-1 text-sm font-bold">Assigned</p></div><div className="rounded-xl bg-[#F8FAFC] p-4"><CalendarDays size={17} className="text-[#0475FB]"/><p className="mt-3 text-[10px] font-bold uppercase text-[#7B8497]">Internship</p><p className="mt-1 text-sm font-bold">Under supervision</p></div><div className="rounded-xl bg-[#F8FAFC] p-4"><ClipboardList size={17} className="text-[#0475FB]"/><p className="mt-3 text-[10px] font-bold uppercase text-[#7B8497]">Tasks</p><p className="mt-1 text-sm font-bold">View task workspace</p></div></div></section><div className="mt-5 grid gap-4 sm:grid-cols-2"><button onClick={()=>navigate("/company/trainer/tasks")} className="rounded-2xl border bg-white p-5 text-left shadow-sm hover:bg-[#F8FAFC]" style={{borderColor:"#E9EDF4"}}><ClipboardList className="text-[#0475FB]" size={20}/><h2 className="mt-3 font-extrabold">Tasks</h2><p className="mt-1 text-xs text-[#7B8497]">Review assignments and submissions in the task workspace.</p></button><button onClick={()=>navigate("/company/trainer/students")} className="rounded-2xl border bg-white p-5 text-left shadow-sm hover:bg-[#F8FAFC]" style={{borderColor:"#E9EDF4"}}><GraduationCap className="text-[#0475FB]" size={20}/><h2 className="mt-3 font-extrabold">Trainee list</h2><p className="mt-1 text-xs text-[#7B8497]">Return to the complete list of students under your supervision.</p></button></div></div></main></div>;
}
