import React, { useEffect, useMemo, useState } from "react";
import { AlertCircle, Bell, Building2, CheckCircle2, ClipboardList, Clock3, GraduationCap, MessageCircle, Plus, RefreshCw, UserCheck, Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import Sidebar from "../../layout/Sidebar";
import { useAuth } from "../../../context/AuthContext";
import { useToast } from "../../../context/ToastContext";
import { trainerAPI } from "../../../services/api";

const BORDER = "#E9EDF4";
const MUTED = "#7B8497";
const navItems = [
  { label: "Dashboard", icon: () => <span>▦</span>, path: "/company/trainer/dashboard" },
  { label: "Trainees", icon: Users, path: "/company/trainer/students" },
  { label: "Tasks", icon: ClipboardList, path: "/company/trainer/tasks" },
  { label: "Applications", icon: UserCheck, path: "/company/trainer/applications" },
];
const getName = (item) => `${item?.student?.user?.firstName || ""} ${item?.student?.user?.lastName || ""}`.trim() || "Student";
const normalize = (r) => r?.data || r || [];

function Header({ user, name, onLogout, pending }) {
  const navigate = useNavigate();
  const initials = name.split(" ").map((x) => x[0]).join("").slice(0, 2).toUpperCase();
  return <header className="mb-6 flex items-center gap-3"><div className="relative flex-1"><div className="h-11 rounded-full border bg-white px-4 flex items-center text-xs text-[#9AA3B2]" style={{borderColor:BORDER}}>Use the dashboard to find trainees, tasks and pending actions</div></div><button onClick={()=>navigate("/company/trainer/applications")} className="relative hidden h-11 w-11 items-center justify-center rounded-full border bg-white sm:flex" style={{borderColor:BORDER}} title="Applications"><Bell size={18} className="text-[#0475FB]"/>{pending>0&&<span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-red-500"/>}</button><button onClick={()=>navigate("/company/trainer/messages")} className="hidden h-11 w-11 items-center justify-center rounded-full border bg-white sm:flex" style={{borderColor:BORDER}} title="Messages"><MessageCircle size={18} className="text-[#0475FB]"/></button><button onClick={()=>navigate("/company/trainer/dashboard")} className="flex items-center gap-2 rounded-full border bg-white py-1.5 pl-1.5 pr-3" style={{borderColor:BORDER}}><div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#EAF3FF] text-[10px] font-extrabold text-[#0475FB]">{initials}</div><span className="hidden text-xs font-bold sm:block">{name}</span></button></header>;
}

function Stat({ icon: Icon, label, value, hint, onClick }) {
  return <button onClick={onClick} className="group rounded-2xl border bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md" style={{borderColor:BORDER}}><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-[#7B8497]">{label}</p><p className="mt-1 text-2xl font-extrabold tracking-tight">{value}</p><p className="mt-1 text-[10px] text-[#9AA3B2]">{hint}</p></div><div className="rounded-xl bg-[#EAF3FF] p-2.5 text-[#0475FB]"><Icon size={18}/></div></div></button>;
}

export default function TrainerDashboard() {
  const navigate = useNavigate(); const { user, logout } = useAuth(); const { showToast } = useToast();
  const [dashboard, setDashboard] = useState(null); const [applications, setApplications] = useState([]); const [students, setStudents] = useState([]); const [tasks, setTasks] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const name = `${user?.firstName || ""} ${user?.lastName || ""}`.trim() || "Trainer";
  const load = async () => { setLoading(true); setError(""); try { const [d,a,s,t] = await Promise.all([trainerAPI.getDashboard(),trainerAPI.getPendingApplications(1,5),trainerAPI.getMyStudents(1,6),trainerAPI.getTasks(1,6)]); setDashboard(d||{}); setApplications(normalize(a)); setStudents(normalize(s)); setTasks(normalize(t)); } catch(e){setError(e?.message||"Unable to load your trainer workspace.");} finally{setLoading(false);} };
  useEffect(()=>{load();},[]);
  const stats = dashboard?.stats || {};
  const activeTasks = stats.activeTasks ?? tasks.filter(t=>!["Completed","Cancelled"].includes(t?.status)).length;
  const completedTasks = stats.completedTasks ?? tasks.filter(t=>t?.status === "Completed").length;
  const pending = stats.pendingApplications ?? applications.length;
  const attention = useMemo(()=>tasks.filter(t=>["Submitted","Under Review"].includes(t?.status)).slice(0,4),[tasks]);
  const approve = async (id) => { try { await trainerAPI.approveApplication(id); showToast("Application approved.","success"); load(); } catch(e){showToast(e?.message||"Could not approve application.","error");} };
  const reject = async (id) => { try { await trainerAPI.rejectApplication(id); showToast("Application rejected.","success"); load(); } catch(e){showToast(e?.message||"Could not reject application.","error");} };
  const signOut = ()=>{logout();navigate("/login")};
  return <div className="flex min-h-screen w-full bg-[#F5F7FB] font-['Inter'] text-[#172033]"><Sidebar navItems={navItems} footerItems={[]} user={{name,role:"Company Trainer",avatar:user?.profileImage||""}} profilePath="/company/trainer/dashboard" onSignOut={signOut} brandPath="/company/trainer/dashboard" storageKey="sidebar-company-trainer"/><main className="min-w-0 flex-1 overflow-y-auto"><div className="mx-auto max-w-[1240px] px-5 py-5 sm:px-8 lg:px-10"><Header user={user} name={name} onLogout={signOut} pending={pending}/>{error&&<div className="mb-4 flex gap-2 rounded-xl border border-red-100 bg-red-50 p-3 text-xs text-red-700"><AlertCircle size={15}/>{error}</div>}<div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[#7B8497]">Company training workspace</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight sm:text-3xl">Welcome back, {name.split(" ")[0]}</h1><p className="mt-1.5 flex items-center gap-1.5 text-sm text-[#7B8497]"><Building2 size={15}/> {dashboard?.company?.name || "Your company"} · Company Trainer</p></div><button onClick={()=>navigate("/company/trainer/tasks")} className="flex items-center justify-center gap-2 rounded-xl bg-[#0475FB] px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-[#035CC9]"><Plus size={17}/> Assign a task</button></div>
      <section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat icon={GraduationCap} label="Trainees" value={loading?"—":(stats.totalStudents??students.length)} hint="Currently assigned" onClick={()=>navigate("/company/trainer/students")}/><Stat icon={ClipboardList} label="Active tasks" value={loading?"—":activeTasks} hint="Need monitoring" onClick={()=>navigate("/company/trainer/tasks")}/><Stat icon={Clock3} label="Awaiting review" value={loading?"—":attention.length} hint="Submissions to review" onClick={()=>navigate("/company/trainer/tasks")}/><Stat icon={UserCheck} label="Applications" value={loading?"—":pending} hint="Need your decision" onClick={()=>navigate("/company/trainer/applications")}/></section>
      <div className="mt-6 grid gap-5 xl:grid-cols-[1.35fr_.9fr]"><section className="rounded-2xl border bg-white p-5 shadow-sm" style={{borderColor:BORDER}}><div className="flex items-start justify-between"><div><h2 className="font-extrabold">Needs your attention</h2><p className="mt-1 text-xs text-[#7B8497]">Start with the work that is waiting on you.</p></div><button onClick={()=>navigate("/company/trainer/tasks")} className="text-xs font-bold text-[#0475FB]">View tasks</button></div>{attention.length===0?<div className="mt-7 rounded-xl bg-[#F8FAFC] p-7 text-center"><CheckCircle2 size={27} className="mx-auto text-[#22C55E]"/><p className="mt-2 text-sm font-bold">You're all caught up</p><p className="mt-1 text-xs text-[#7B8497]">No trainee submissions are waiting for review.</p></div>:<div className="mt-4 divide-y">{attention.map(t=><div key={t.id} className="flex items-center gap-3 py-3"><div className="rounded-lg bg-[#FFF4E5] p-2 text-[#D9821B]"><ClipboardList size={16}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{t?.title||t?.name||"Task submission"}</p><p className="mt-0.5 text-xs text-[#7B8497]">{getName(t)} · {t?.status||"Submitted"}</p></div><button onClick={()=>navigate("/company/trainer/tasks")} className="rounded-lg bg-[#EAF3FF] px-3 py-2 text-[11px] font-bold text-[#0475FB]">Review</button></div>)}</div>}</section>
      <section className="rounded-2xl border bg-white p-5 shadow-sm" style={{borderColor:BORDER}}><div className="flex items-start justify-between"><div><h2 className="font-extrabold">Pending applications</h2><p className="mt-1 text-xs text-[#7B8497]">Students waiting for your decision.</p></div><button onClick={()=>navigate("/company/trainer/applications")} className="text-xs font-bold text-[#0475FB]">View all</button></div>{applications.length===0?<div className="mt-7 py-7 text-center"><UserCheck size={28} className="mx-auto text-[#C9D0DB]"/><p className="mt-2 text-sm font-bold">No pending applications</p></div>:<div className="mt-4 space-y-3">{applications.slice(0,4).map(a=><div key={a.id} className="rounded-xl border p-3" style={{borderColor:BORDER}}><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#EAF3FF] text-xs font-extrabold text-[#0475FB]">{getName(a).charAt(0)}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{getName(a)}</p><p className="truncate text-[10px] text-[#7B8497]">{a?.student?.major||"Major not provided"}</p></div></div><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={loading} onClick={()=>reject(a.id)} className="rounded-lg border border-red-100 py-1.5 text-[10px] font-bold text-red-600 hover:bg-red-50">Reject</button><button disabled={loading} onClick={()=>approve(a.id)} className="rounded-lg bg-[#0475FB] py-1.5 text-[10px] font-bold text-white hover:bg-[#035CC9]">Approve</button></div></div>)}</div>}</section></div>
      <section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm" style={{borderColor:BORDER}}><div className="flex items-center justify-between"><div><h2 className="font-extrabold">My trainees</h2><p className="mt-1 text-xs text-[#7B8497]">A quick view of the people you supervise.</p></div><button onClick={()=>navigate("/company/trainer/students")} className="text-xs font-bold text-[#0475FB]">Manage trainees</button></div>{students.length===0?<div className="mt-5 rounded-xl bg-[#F8FAFC] p-6 text-center text-xs text-[#7B8497]">No trainees assigned yet.</div>:<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{students.slice(0,6).map(s=><button key={s.id} onClick={()=>navigate("/company/trainer/students")} className="flex items-center gap-3 rounded-xl border p-3 text-left transition hover:bg-[#F8FAFC]" style={{borderColor:BORDER}}><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#FFF4E5] text-xs font-extrabold text-[#C87512]">{getName(s).charAt(0)}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{getName(s)}</p><p className="truncate text-[10px] text-[#7B8497]">{s?.student?.major||"Major not provided"}</p></div><Users size={14} className="text-[#B0B7C3]"/></button>)}</div>}</section>
      <div className="mt-5 flex items-center justify-between rounded-2xl border bg-white px-5 py-4 text-xs" style={{borderColor:BORDER}}><div className="flex items-center gap-2 text-[#7B8497]"><RefreshCw size={14}/><span>Keep the workflow simple: <b className="text-[#172033]">see → understand → act → confirm.</b></span></div><button onClick={load} className="font-bold text-[#0475FB]">Refresh workspace</button></div>
    </div></main></div>;
}
